CREATE TABLE [HR].[Employees]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[fullname] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [HR].[Employees] ADD CONSTRAINT [PK__Employee__3214EC0737B7DFF5] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
